when:
  event:
    - push
    - manual

steps:
  build_and_deploy:
    image: docker:27.3-cli
    pull: true
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker compose down
      - docker compose up -d --build --force-recreate
